# Generated by Django 2.1.3 on 2018-11-27 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MinorPlanet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('inclination', models.FloatField()),
                ('node', models.FloatField()),
                ('peri', models.FloatField()),
                ('semimajor', models.FloatField()),
                ('motion', models.FloatField()),
                ('eccentricity', models.FloatField()),
                ('anomaly', models.FloatField()),
                ('packed_epoch', models.CharField(max_length=5)),
                ('equinox_year', models.CharField(max_length=4)),
                ('magnitude_model', models.CharField(max_length=16)),
            ],
        ),
    ]
